"""
Models for Customers
All of the models are stored in this module
"""
import uuid
import logging
from datetime import datetime

from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy import CheckConstraint, Index
from sqlalchemy.exc import IntegrityError

logger = logging.getLogger("flask.app")

# SQLAlchemy handle used by the app
db = SQLAlchemy()


class DataValidationError(Exception):
    """Used for data validation errors when persisting/deserializing"""


class Customers(db.Model):
    """
    Class that represents a customer
    """

    __tablename__ = "customers"

    ##################################################
    # Table Schema
    ##################################################
    id = db.Column(
        PGUUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,   # generated by server/app on insert
        nullable=False,
    )
    first_name = db.Column(db.String(50), nullable=False)
    last_name = db.Column(db.String(50), nullable=False)
    address = db.Column(db.Text, nullable=False)
    created_at = db.Column(db.DateTime, nullable=False, server_default=db.func.now())
    updated_at = db.Column(
        db.DateTime,
        nullable=False,
        server_default=db.func.now(),
        onupdate=db.func.now(),
    )

    __table_args__ = (
        CheckConstraint("length(trim(address)) > 0", name="ck_customers_address_not_blank"),
        Index("idx_customers_last_name", "last_name"),
    )

    ##################################################
    # Instance methods
    ##################################################
    def __repr__(self) -> str:
        return f"<Customer {self.first_name} {self.last_name} id=[{self.id}]>"

    def create(self):
        """Persists the customer to the database"""
        logger.info("Creating customer %s %s", self.first_name, self.last_name)
        try:
            db.session.add(self)
            db.session.commit()
        except (IntegrityError, Exception) as e:  # noqa: BLE001
            db.session.rollback()
            logger.error("Error creating record: %s", self)
            raise DataValidationError(e) from e

    def update(self):
        """Updates a customer in the database"""
        if not self.id:
            raise DataValidationError("Update called with empty 'id'")
        logger.info("Updating customer %s %s", self.first_name, self.last_name)
        try:
            db.session.commit()
        except (IntegrityError, Exception) as e:  # noqa: BLE001
            db.session.rollback()
            logger.error("Error updating record: %s", self)
            raise DataValidationError(e) from e

    def delete(self):
        """Removes a customer from the data store"""
        if not self.id:
            raise DataValidationError("Delete called with empty 'id'")
        logger.info("Deleting customer %s %s", self.first_name, self.last_name)
        try:
            db.session.delete(self)
            db.session.commit()
        except (IntegrityError, Exception) as e:  # noqa: BLE001
            db.session.rollback()
            logger.error("Error deleting record: %s", self)
            raise DataValidationError(e) from e

    def serialize(self) -> dict:
        """Serializes a customer into a dictionary"""
        return {
            "id": str(self.id) if self.id else None,
            "first_name": self.first_name,
            "last_name": self.last_name,
            "address": self.address,
            "created_at": (
                self.created_at.isoformat()
                if isinstance(self.created_at, datetime)
                else None
            ),
            "updated_at": (
                self.updated_at.isoformat()
                if isinstance(self.updated_at, datetime)
                else None
            ),
        }

    def deserialize(self, data: dict):
        """Deserializes a customer from a dictionary"""
        if not isinstance(data, dict):
            raise DataValidationError("Invalid Customers: body must be a dictionary")

        try:
            first_name = data["first_name"]
            last_name = data["last_name"]
            address = data["address"]
        except KeyError as error:
            raise DataValidationError(f"Invalid customers: missing {error.args[0]}") from error

        # strip whitespace
        if isinstance(first_name, str):
            first_name = first_name.strip()
        if isinstance(last_name, str):
            last_name = last_name.strip()
        if isinstance(address, str):
            address = address.strip()

        if not first_name:
            raise DataValidationError("first_name must be non-empty")
        if not last_name:
            raise DataValidationError("last_name must be non-empty")
        if not address:
            raise DataValidationError("address must be non-empty")

        self.first_name = first_name
        self.last_name = last_name
        self.address = address
        return self

    ##################################################
    # Class methods
    ##################################################
    @classmethod
    def all(cls):
        """Returns all customers in the database"""
        logger.info("Processing all customers")
        return cls.query.all()

    @classmethod
    def find(cls, by_id):
        """Finds a customer by its ID"""
        logger.info("Processing lookup for id %s ...", by_id)
        return cls.query.session.get(cls, by_id)

    @classmethod
    def find_by_last_name(cls, last_name: str, fuzzy: bool = False):
        """Returns customers filtered by last_name"""
        if fuzzy:
            return cls.query.filter(cls.last_name.ilike(f"%{last_name}%"))
        return cls.query.filter(cls.last_name == last_name)

    @classmethod
    def find_by_first_name(cls, first_name: str, fuzzy: bool = False):
        """Returns customers filtered by first_name"""
        if fuzzy:
            return cls.query.filter(cls.first_name.ilike(f"%{first_name}%"))
        return cls.query.filter(cls.first_name == first_name)

    @classmethod
    def find_by_name(cls, name: str, fuzzy: bool = True):
        """Search by name: single token or 'First Last'"""
        if not name:
            return cls.query.filter(False)  # empty result
        tokens = name.strip().split()
        if len(tokens) == 1:
            token = tokens[0]
            if fuzzy:
                return cls.query.filter(
                    (cls.first_name.ilike(f"%{token}%")) | (cls.last_name.ilike(f"%{token}%"))
                )
            return cls.query.filter((cls.first_name == token) | (cls.last_name == token))
        # two or more tokens -> use first and last
        first, last = tokens[0], tokens[-1]
        if fuzzy:
            return cls.query.filter(
                cls.first_name.ilike(f"%{first}%"), cls.last_name.ilike(f"%{last}%")
            )
        return cls.query.filter(cls.first_name == first, cls.last_name == last)
